# % ../conf_pieces/global_linuxBrokenTest.conf
% ../conf_pieces/global_default.conf
% ../conf.d

# [/test_notMedia]
#     /home/joelwindows7/.local/mnt/test_notMedia
#     % ../conf_pieces/accs_default_noAccident.conf

[/test_notMedia_bound]
    /home/joelwindows7/.local/mnt/test_notMedia_bound
    % ../conf_pieces/accs_default_noAccident.conf
    % ../conf_pieces/flags_null.conf

[/test_notMedia_symlink]
    /home/joelwindows7/.local/mnt/test_notMedia_symlink
    % ../conf_pieces/accs_default_noAccident.conf
    # with that, you cannot have the `/test_notMedia` anymore
    # since it'll complain `same .hist path`
    # Like you can only have either!
    % ../conf_pieces/flags_null.conf